version: "3.1"

services:
  web:
    build: .
    restart: always
    container_name: "app_django"
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'


  redis:
    image: redis
    restart: always
    container_name: 'demo_app_redis'
    command: redis-server
    ports:
      - '6379:6379'

  celery:
    build: .
    container_name: 'demo_app_celery'
    command: celery -A Diplom worker -B
    links:
      - redis
    depends_on:
      - web
      - redis


