# Generated by Django 4.1.6 on 2023-04-12 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, unique=True, verbose_name='Код')),
                ('coordinates', models.CharField(max_length=30, null=True, verbose_name='Координаты')),
                ('apiary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hives.apiary', verbose_name='Пасека')),
            ],
        ),
        migrations.CreateModel(
            name='ListOfHives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.hive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataHive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=30, null=True, verbose_name='Координаты')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.FloatField(verbose_name='Влажность')),
                ('is_swarming', models.BooleanField(default=False, verbose_name='Роение')),
                ('is_robber', models.BooleanField(default=False, verbose_name='Украли')),
                ('is_robbed', models.BooleanField(default=False, verbose_name='Обокрали')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.hive', verbose_name='Улей')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=30, null=True, verbose_name='Координаты')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField(verbose_name='Вес')),
                ('temperature', models.FloatField(verbose_name='Температура')),
                ('humidity', models.FloatField(verbose_name='Влажность')),
                ('is_swarming', models.BooleanField(default=False, verbose_name='Роение')),
                ('is_robber', models.BooleanField(default=False, verbose_name='Украли')),
                ('is_robbed', models.BooleanField(default=False, verbose_name='Обокрали')),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hives.hive', verbose_name='Улей')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
