# Generated by Django 4.1.6 on 2023-05-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hives', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiary',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
    ]
