# Generated by Django 4.1.6 on 2023-04-14 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivedetectormodel',
            name='obj',
            field=models.BinaryField(max_length=5000),
        ),
    ]
